### ISSUE TITLE
XML Schema support

### ISSUE THREAD

**Issue by kringol** [tajakobsen/unxml#7]
Support for defining the types and arrays by passing an XML Schema indicating the datatype of each xml field and whether it is an array or not.

**Comment by tajakobsen** [comment]
If you are working with XML Schemas you would usually do a 1 to 1 mapping between xml and json. I think other libraries does this very well.

unXml usually maps to a completly different structure in Json, so I don't think the Schema would be of much value here.

When it comes to validating the xml, that should probably be done before the Node is passed to the parser.
